import React, { useState, useEffect } from 'react';
import Markdown from './components/Markdown';
import './App.css';

interface MarkdownInfo {
  fileName: string;
  time: string;
  title: string;
  tags: string[];
}

const App: React.FC = () => {
  const [markdownText, setMarkdownText] = useState('');

  useEffect(() => {
    // this list generated by script
    // which called in github workflows
    // when push
    fetch(`${window.location.pathname}blogList.json`)
    .then(response => response.json())
    .then((json: MarkdownInfo[]) => {
      fetch(`${window.location.pathname}articles/${json[0].fileName}`)
      .then(response => response.text())
      .then(text => setMarkdownText(text))
      .catch(err => console.log(err));
    })
    .catch(err => console.log(err));

  }, []);

  return (
    <div className="App">
      <Markdown markdownText={markdownText} />
    </div>
  );
}

export default App;
